services:
  ypd-minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: ypd-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - ypd-network
    volumes:
      - ypd-minio-volume:/data:rw
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped

  ypd-redis:
    image: redis:8.2.1-bookworm
    container_name: ypd-redis
    ports:
      - "6379:6379"
    networks:
      - ypd-network
    volumes:
      - ypd-redis-volume:/data:rw
    restart: unless-stopped

  ypd-backend:
    depends_on:
      - ypd-minio
      - ypd-redis
    image: ghcr.io/ximaz/youtube-playlist-downloader/backend
    container_name: ypd-backend
    env_file: ../web/backend/.env.production.local
    ports:
      - "8080:3000"
    networks:
      - ypd-network
    restart: unless-stopped

  ypd-frontend:
    depends_on:
      - ypd-backend
    image: ghcr.io/ximaz/youtube-playlist-downloader/frontend
    env_file: ../web/frontend/.env.production.local
    container_name: ypd-frontend
    ports:
      - "8081:3001"
    networks:
      - ypd-network
    restart: unless-stopped

volumes:
  ypd-minio-volume:
  ypd-redis-volume:

networks:
  ypd-network:
